# Generated by Django 5.1.4 on 2024-12-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Enter Surname')),
                ('name', models.CharField(max_length=100, verbose_name='Enter Name')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Enter Date of Birth')),
                ('place_residence', models.CharField(max_length=100, verbose_name='Enter Place Residence')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
